### PR TITLE
add data

### PR DESCRIPTION
**Pull request by karn21**

### CODE REVIEW

**Comment by Taiwrash** [comment]
@all-contributors please add @karn21  for infrastructure, tests and code

**Review by Taiwrash — CHANGES_REQUESTED** [review]
Great job! @karn21 but there's an extra curly bracket at the top of your data in the `data.json`. fix it and your PR will get merged in no time

**Comment by karn21** [comment]
> Great job! @karn21 but there's an extra curly bracket at the top of your data in the `data.json`. fix it and your PR will get merged in no time

I have checked and I could not find an extra curly bracket. I think the issue was the trailing comma which I have removed. Please see the attached image.
Untitled

**Review by Taiwrash — APPROVED** [review]

**Comment by Taiwrash** [comment]
@all-contributors please add @karn21 for infrastructure, tests and code

**Pull request merged**
